const {
    MONGOURI,
    NODE_ENV,
    EXPIRATION,
    JWTSECRET,
    AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY,
    AWS_REGION,
    AWS_S3_BUCKET,
} = process.env

export const env = () => ({
    MONGOURI: MONGOURI,
    NODE_ENV: NODE_ENV,
    EXPIRATION: EXPIRATION,
    JWTSECRET: JWTSECRET,
    AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY,
    AWS_REGION: AWS_REGION,
    AWS_S3_BUCKET: AWS_S3_BUCKET
})